# account service properties
server:
  port: 8081

spring:
  kafka:
    consumer:
      enable-auto-commit: false

  application:
    name: import-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: product
    password: 123456
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase: #liquibase changelog properties
    enabled: true
    change-log: classpath:db/db-changelog-master.yaml

api:
  batch_size: 50000
  insert_batch_size: 1000
  csv:
    foldername: csvfolder
#kafka:
#  bootstrapAddress: localhost:9092
#  tenant-topic: invoice2
#  req-tenant-topic: local2.req-tenant
#  journal-topic: local2.journal
#  group-id: p.group-reality
#  opening-balance-topic: p.product1
